stages:
  data_ingestion:
    cmd: python -m src.safeguard_ai.ml.ingestion
    deps:
      - src/safeguard_ai/ml/common.py
      - src/safeguard_ai/ml/ingestion.py
      - params.yaml
      - data/raw_data/fraud_dataset.csv
    outs:
      - data/raw_data/dataset.csv

  training:
    cmd: python -m src.safeguard_ai.ml.training
    deps:
      - src/safeguard_ai/ml/common.py
      - src/safeguard_ai/ml/training.py
      - data/raw_data/dataset.csv
    params:
      - train.learning_rate
      - train.model_name
      - train.model_output_dir
      - train.batch_size
      - train.epochs
      - train.save_steps
    outs:
      - models/fraud_model_final

  evaluation:
    cmd: python -m src.safeguard_ai.ml.evaluation
    deps:
      - src/safeguard_ai/ml/common.py
      - src/safeguard_ai/ml/evaluation.py
      - models/fraud_model_final
      - data/raw_data/dataset.csv
    metrics:
      - metrics.json:
          cache: false
