name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Full history fetch karne ke liye

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Git configuration
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Hugging Face repository ko remote ki tarah add karein
          # Username: sainivipin | Repo: SafeGuard-Live
          git remote add hf https://sainivipin:$HF_TOKEN@huggingface.co/spaces/sainivipin/SafeGuard-Live
          
          # Force push karein (ya normal push agar history match karti hai)
          git push --force hf main