name: Sync to Hugging Face Docker Space

on:
  push:
    branches:
      - main  # Jab bhi main branch par push hoga, ye chalega
      - master

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Agar aapke paas large model files hain toh ye zaruri hai

      - name: Push Code and Dockerfile to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Apna Hugging Face username aur Space name niche check kar lein
          git remote add hf https://sainivipin:$HF_TOKEN@huggingface.co/spaces/sainivipin/SafeGuard-Live
          
          # Ye command aapka code Hugging Face par push kar degi
          git push --force hf main